sudo: required
language: generic
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_80e2839b8039_key -iv $encrypted_80e2839b8039_iv -in deploy_key.enc -out ./deploy_key -d
install:
script:
  - make container
  - make run
cache:
  directories:
    - mirror
env:
  global:
    secure: iSh8IuAFsrxnjTymiwnIsSSaDDe4MTyt+G2/zK7txVRGkFCLk+QEnKRbU7f3IXKjU0Rn8xcm+LsxBoOudfDkDP7TL0RqQ5qe/NM+UnN5W3W+SZd86n3IHYk+Cehi7f2ujuzPXafD27DfvKAYql9Vg72ZnAXNncHEJBUPOwbRXVMMj7lwpYAbv/l+A6lw1xDBoT5U9QiJyvziFHnZ3s6J9uS9pTwl1BKNXL8t0IiFeGUAGXP5HYIx9SPVI+xz2pgtpznvXZ7WZtUCp3eKja2C/7HcxK1incQmZxUXeKCdBmyD29QKkO6kZUMWubFStzef6qtgFr8AwLY2BTowREcrL7sAHWVOcE4M0yMwzhjWnS0iujxww0K2/MIf9RHyLqXQbc2HEe/i9Aa8wK6/vM2DoVAowbvOBM8B+3RudgmixT3mC/4TptLQq82tCSJXrvLO9iK2uqDD7zK+zsG3yqeV3WoQc7KeoKjFu3eRg9onM43EihW28m5cREwV2VH84wIhujP4QTWdTnm6BDzHP4CX60Y2qbxm6nQDKsqedhf4LjiGDZi2o9AhL/mfMCbab1urpGii+QEvMZa1Mz4mNvSFvbbWDQYG7Pwh+GU6YUs0EtIAPAr5ktV1COmrfgEFDoj9tTUFRwPf1ZzM2Isr3TU6+j1yXEfLsleqF9B4FnoWuJY=
