sudo: required
language: generic
services:
- docker
install: 
script:
- make container
- make run
cache:
  directories:
  - mirror
before_install:
- openssl aes-256-cbc -K $encrypted_80e2839b8039_key -iv $encrypted_80e2839b8039_iv
  -in deploy_key.enc -out ./deploy_key -d
